"""
Django settings for buswebsite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment overrides from 'local_settings.py' if present.
# This file can set os.environ variables for development (keep it out of VCS).
_local_settings_path = os.path.join(BASE_DIR, 'local_settings.py')
if os.path.exists(_local_settings_path):
    try:
        with open(_local_settings_path, 'r', encoding='utf-8') as _f:
            _code = compile(_f.read(), _local_settings_path, 'exec')
            exec(_code, globals())
    except Exception:
        pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY: load sensitive settings from environment where possible
# In production set DJANGO_SECRET_KEY and DJANGO_DEBUG appropriately.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-^qn)$tc2yr4dpoao*vlh7xilr96y%x6e!lf+)aeyv*$q33k!$m')

# Note: DEBUG defaults to 'True' for local development. Set DJANGO_DEBUG='False'
# in production to disable Django debug pages and enable stricter headers.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# ALLOWED_HOSTS should be explicitly set in production (comma-separated).
# Default to the project's production domains so the app works if env var is
# not set during an initial deploy.
_raw_allowed = os.environ.get('ALLOWED_HOSTS', 'diellerbus.com,www.diellerbus.com,diellerbus.onrender.com')
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(',') if h.strip()]

# Populate CSRF_TRUSTED_ORIGINS from ALLOWED_HOSTS (use https://<host>),
# unless an explicit env var is provided.
_raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', ','.join(['https://' + h for h in ALLOWED_HOSTS if h and h != '*']))
CSRF_TRUSTED_ORIGINS = [u.strip() for u in _raw_csrf.split(',') if u.strip()]

# When running with DEBUG enabled, allow common local development hosts so
# the development server and local editors can access the site without
# triggering DisallowedHost errors (for example, 127.0.0.1:8000).
if DEBUG:
    for _local in ('127.0.0.1', 'localhost'):
        if _local not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.insert(0, _local)

# Ensure production domain is present in ALLOWED_HOSTS so pushes that don't set
# the env var still allow the public site to run. Also ensure CSRF trusted
# origins include the https:// form of the site.
for _host in ('diellerbus.com', 'www.diellerbus.com'):
    try:
        if _host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_host)
    except Exception:
        pass

try:
    if not any('diellerbus.com' in u for u in CSRF_TRUSTED_ORIGINS):
        CSRF_TRUSTED_ORIGINS.append('https://diellerbus.com')
        if 'www.diellerbus.com' not in ''.join(CSRF_TRUSTED_ORIGINS):
            CSRF_TRUSTED_ORIGINS.append('https://www.diellerbus.com')
except Exception:
    try:
        CSRF_TRUSTED_ORIGINS = (CSRF_TRUSTED_ORIGINS or []) + ['https://diellerbus.com', 'https://www.diellerbus.com']
    except Exception:
        CSRF_TRUSTED_ORIGINS = ['https://diellerbus.com', 'https://www.diellerbus.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

# Optional Channels integration (only enable if package available)
try:
    import channels  # type: ignore
except Exception:
    CHANNELS_AVAILABLE = False
else:
    CHANNELS_AVAILABLE = True

if CHANNELS_AVAILABLE:
    INSTALLED_APPS += ['channels']
    ASGI_APPLICATION = 'buswebsite.asgi.application'
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer'
        }
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # static file serving
    'main.middleware.security_headers.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'buswebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'buswebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'Europe/Kiev'

# Allow disabling Django i18n loading via environment for faster startup during
# local debugging (set DJANGO_USE_I18N='False' to disable).
USE_I18N = os.environ.get('DJANGO_USE_I18N', 'True') == 'True'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
from django.core.exceptions import ImproperlyConfigured


def _get_env(key, default=None, cast=None, required_in_prod=False):
    v = os.environ.get(key, default)
    if v is None:
        if required_in_prod and not DEBUG:
            raise ImproperlyConfigured(f"{key} environment variable is required in production")
        return v
    if cast:
        try:
            if cast is bool:
                return str(v).lower() in ('1', 'true', 'yes')
            return cast(v)
        except Exception:
            raise ImproperlyConfigured(f"Invalid value for {key}")
    return v


# Email configuration (Brevo SMTP). Values must be supplied via environment
# variables in production. Defaults are lenient for local development only.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
# Do not raise during import for missing email env vars; keep a fallback where appropriate.
EMAIL_HOST = _get_env('EMAIL_HOST', None, cast=str, required_in_prod=False) or os.environ.get('EMAIL_HOST', 'smtp-relay.brevo.com')
EMAIL_PORT = _get_env('EMAIL_PORT', '587', cast=int)
EMAIL_USE_TLS = _get_env('EMAIL_USE_TLS', 'True', cast=bool)
EMAIL_USE_SSL = _get_env('EMAIL_USE_SSL', 'False', cast=bool)
if EMAIL_USE_SSL:
    EMAIL_USE_TLS = False
EMAIL_HOST_USER = _get_env('EMAIL_HOST_USER', None, cast=str, required_in_prod=False)
EMAIL_HOST_PASSWORD = _get_env('EMAIL_HOST_PASSWORD', None, cast=str, required_in_prod=False)

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or (f"Dieller Bus <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else None)
# Only enforce DEFAULT_FROM_EMAIL in production when a real SMTP backend is configured.
if not DEFAULT_FROM_EMAIL and not DEBUG and EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    raise ImproperlyConfigured('DEFAULT_FROM_EMAIL environment variable is required in production when using SMTP')

# Comma-separated list of usernames or emails that should be allowed access
# to support/admin endpoints in addition to staff users. Example: "dieller,ops@org.com"
SUPPORT_ADMINS = [u.strip() for u in os.environ.get('SUPPORT_ADMINS', '').split(',') if u.strip()]

# Stripe
STRIPE_PUBLIC_KEY = ""
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")
# LiqPay (use environment variables for keys)
LIQPAY_PUBLIC_KEY = os.environ.get("LIQPAY_PUBLIC_KEY", "")
LIQPAY_PRIVATE_KEY = os.environ.get("LIQPAY_PRIVATE_KEY", "")
# When True, accept LiqPay callbacks even if signature verification fails.
# Use only for emergency/manual reconciliation (opt-in via env).
LIQPAY_ALLOW_UNVERIFIED = os.environ.get('LIQPAY_ALLOW_UNVERIFIED', 'False') == 'True'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Security-related cookie and header defaults (adjust via environment)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# Static files (WhiteNoise)
# Prefer manifest storage in production for hashed filenames. If the
# manifest hasn't been generated (collectstatic not run) or the
# `DISABLE_MANIFEST_STORAGE` env var is set to 'True', fall back to the
# non-manifest storage so the site can still serve static files.
_manifest_storage = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
_fallback_storage = 'whitenoise.storage.CompressedStaticFilesStorage'
if os.environ.get('DISABLE_MANIFEST_STORAGE', 'False') == 'True':
    STATICFILES_STORAGE = _fallback_storage
else:
    try:
        _manifest_file = os.path.join(STATIC_ROOT, 'staticfiles.json')
        if os.path.exists(_manifest_file):
            STATICFILES_STORAGE = _manifest_storage
        else:
            STATICFILES_STORAGE = _fallback_storage
    except Exception:
        STATICFILES_STORAGE = _fallback_storage

# Development convenience defaults: when DEBUG=True make common local
# testing settings safe and easy to use. These defaults can be overridden
# via environment variables in production.
if DEBUG:
    # Use console email backend for local testing unless explicitly set
    EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

    # Ensure local hosts are allowed for the development server
    try:
        if '127.0.0.1' not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.insert(0, '127.0.0.1')
        if 'localhost' not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.insert(1, 'localhost')
    except Exception:
        pass

    # Do not enforce secure cookies/redirects by default in local mode;
    # respect explicit environment overrides if present.
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'

# Logging: write INFO+ logs to a rotating file and to console. Ensure log directory exists.
LOG_DIR = os.path.join(BASE_DIR, 'logs')
try:
    os.makedirs(LOG_DIR, exist_ok=True)
except Exception:
    pass

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'main': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

STATICFILES_STORAGE = STATICFILES_STORAGE

# Redirect unauthenticated users to registration page when protected views are accessed
LOGIN_URL = '/register/'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = STATICFILES_STORAGE
