# Generated by Django 5.2.8 on 2026-04-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_city_route_ticket_from_city_ticket_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
