# Generated by Django 5.2.8 on 2026-04-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trip_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_trips', to='main.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_trips', to='main.city'),
        ),
    ]
