# Generated by Django 5.2.8 on 2026-04-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_trip_end_city_trip_start_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
