# Generated by Django 5.2.8 on 2026-05-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tripstop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва/марка')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buses/', verbose_name='Фото автобуса')),
                ('seats', models.PositiveIntegerField(default=50, verbose_name='Кількість місць')),
                ('contact_name', models.CharField(blank=True, max_length=120, verbose_name='Контактна особа')),
                ('contact_phone', models.CharField(help_text='Формат: +380XXXXXXXXX або локальний', max_length=32, verbose_name='Телефон для замовлення')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Ціна за годину (UAH)')),
                ('price_note', models.CharField(default='Ціна за км уточнюється у водія', max_length=255, verbose_name='Примітка про ціну')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобуси',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(choices=[('UA_PL', 'Україна → Польща'), ('PL_UA', 'Польща → Україна'), ('UA_UA', 'Україна → Україна')], default='UA_PL', max_length=10),
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name="Ім'я замовника")),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон замовника')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата початку')),
                ('time_from', models.TimeField(blank=True, null=True, verbose_name='Час початку')),
                ('hours', models.PositiveIntegerField(default=1, verbose_name='Кількість годин')),
                ('estimated_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Орієнтовні км')),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Орієнтовна ціна')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Коментар/побажання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.bus')),
            ],
            options={
                'verbose_name': 'Бронювання автобуса',
                'verbose_name_plural': 'Бронювання автобусів',
                'ordering': ('-created_at',),
            },
        ),
    ]
