# Generated by Django 5.2.8 on 2026-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_supportpresetquestion_supportticket_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='support_messages/'),
        ),
    ]
