# Generated by Django 5.2.8 on 2026-05-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_profile_avatar_supportmessage_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text="Логін для створення користувача (необов'язково)", max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='support_workers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Працівник техпідтримки',
                'verbose_name_plural': 'Працівники техпідтримки',
            },
        ),
    ]
