# Generated by Django 5.2.8 on 2026-05-08 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_supportworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_international',
            field=models.BooleanField(default=False, verbose_name='Рейс за кордон'),
        ),
        migrations.CreateModel(
            name='TripDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availabilities', to='main.trip')),
            ],
            options={
                'verbose_name': 'Доступність рейсу за датою',
                'verbose_name_plural': 'Доступність рейсу за датою',
                'ordering': ('date',),
                'unique_together': {('trip', 'date')},
            },
        ),
    ]
