# Generated by Django 5.2.8 on 2026-05-09 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ticket_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_carrier',
            field=models.BooleanField(default=False, verbose_name='Профіль перевізника'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='main.trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='carrier_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrier_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('success', 'Успішно'), ('failure', 'Неуспішно'), ('refunded', 'Повернуто')], default='pending', max_length=20),
        ),
    ]
