# Generated by Django 5.2.8 on 2026-05-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_carrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='Dieller Bus', help_text='Найменування магазину / сервісу', max_length=255)),
                ('shop_address', models.CharField(blank=True, help_text='Юридична або поштова адреса', max_length=255)),
                ('contact_email', models.EmailField(blank=True, help_text='Контактний email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Контактний телефон', max_length=32)),
                ('owner_info', models.TextField(blank=True, help_text='Інформація про власника (ФОП/ТОВ, реквізити для відшкодувань тощо)')),
                ('currency', models.CharField(default='UAH', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, help_text='HTML-контент сторінки')),
                ('is_published', models.BooleanField(default=True)),
                ('language', models.CharField(default='uk', help_text='Код мови сторінки', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статична сторінка',
                'verbose_name_plural': 'Статичні сторінки',
                'ordering': ('order', 'title'),
            },
        ),
    ]
