# Generated by Django 5.2.8 on 2026-05-12 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_passwordchangerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.city')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fares', to='main.trip')),
            ],
            options={
                'verbose_name': 'Тариф (пара міст)',
                'verbose_name_plural': 'Тарифи (пари міст)',
                'unique_together': {('trip', 'from_city', 'to_city')},
            },
        ),
    ]
