# Generated by assistant for adding FareFolder and TripFare.folder

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tripfare'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fare_folders', to='main.carrier')),
            ],
            options={
                'verbose_name': 'Папка тарифів',
                'verbose_name_plural': 'Папки тарифів',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='tripfare',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fares', to='main.farefolder'),
        ),
    ]
