# Generated by assistant: add ticket FK to SupportTicket
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0022_farefolder_and_tripfare_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_requests', to='main.ticket'),
        ),
    ]
