# Generated by Django 5.2.8 on 2026-06-24 14:51

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_create_test_trips_fares'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcities', to='main.city', verbose_name='Головне місто'),
        ),
        migrations.AddField(
            model_name='route',
            name='include_subcities',
            field=models.BooleanField(default=False, help_text='Якщо відмічено, підміста рахуються по тарифу головного міста', verbose_name='Включати підміста'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.Bus._bus_image_upload_to, verbose_name='Фото автобуса'),
        ),
    ]
