# Generated by Django on 2026-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_city_parent_route_include_subcities_alter_bus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='business_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='ФОП/ТОВ'),
        ),
    ]
