# Generated by Django 5.2.8 on 2026-07-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_carrier_business_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='business_type',
            field=models.CharField(blank=True, choices=[('FOP', 'ФОП'), ('TOV', 'ТОВ')], max_length=16, verbose_name='Тип юридичної форми'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='business_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер / ІПН'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='wayforpay', max_length=50),
        ),
    ]
